### ISSUE TITLE
[ADDON] - Amazon EFS CSI Driver

### ISSUE THREAD

**Issue by kcoleman731** [aws-quickstart/cdk-eks-blueprints#21] opened 2021-05-25 19:58 UTC
Add support for EFS CSI via an add-on

https://docs.aws.amazon.com/eks/latest/userguide/efs-csi.html

**Comment by camba1** [comment] 2022-03-13 15:51
duplicate of #233

**Comment by youngjeong46** [comment] 2022-04-19 22:51
Closing as finished.

**Closed by youngjeong46** 2022-04-19 22:51 UTC
Labels: add-on
