### ISSUE TITLE
(cluster-providers): tagging ec2 instances

### ISSUE THREAD

**Issue by pflorek** [aws-quickstart/cdk-eks-blueprints#485] opened 2022-08-18 13:31 UTC
### Describe the feature

Propagate tags to EC2 instances.

### Use Case

- Having the `Name` tag propagated to EC2 instances helps us to visually identify node in the EC2 dashboard faster
- While analyzing costs it's very useful to separate by service, team, customer, whatever tags are configured
- Sometimes instance tags are also used by iam policies and considered best practice in some docs
- ...

### Proposed Solution

Always create a NodeGroup with a LaunchTemplate and pass tags

### Other Information

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatetagspecification.html `instance`

### Acknowledgements

- [X] I may be able to implement this feature request

### CDK version used

2.37.1

### EKS Blueprints Version

1.2.0

### Node.js Version

18.7.0

### Environment details (OS name and version, etc.)

MacOS

**Comment by praveenperera** [comment] 2023-03-15 18:54
Is there a workaround for this right now, is it possible to add tags to the cluster provider?

**Comment by shapirov103** [comment] 2023-03-15 18:59
> Is there a workaround for this right now, is it possible to add tags to the cluster provider?

You can check the approach taken in the PR that I linked here #624. It is achievable now by creating a subclass of the `GenericClusterProvider` and applying changes similar to those in the PR. Or you can wait just a bit, once the PR is merged, we will release 1.6.1 with this support.

**Comment by praveenperera** [comment] 2023-03-15 19:03
@shapirov103 thanks for the quick response, that's exactly what I need the `customTags` I'll wait for that PR thanks.

**Comment by elamaran11** [comment] 2023-05-03 18:10
@praveenperera Are you good to close this Issue. The issue is fixed.

**Closed** 2023-05-03 18:18 UTC
Labels: feature
