### ISSUE TITLE
cdk deploy: State functionActiveV2 not found.

### ISSUE THREAD

**Issue by imshashank** [aws-quickstart/cdk-eks-blueprints#629] opened 2023-03-25 22:52 UTC
### Describe the bug

cdk version: aws-cdk@2.66.1
node version v19.8.1
region: us-east-1

```
10:16:53 PM | CREATE_FAILED        | Custom::AWSCDK-EKS-HelmChart          | magicapi-eks/chart...r/Resource/Default
Received response status [FAILED] from custom resource. Message returned: StateNotFoundError: State functionActiveV2 not found.
at constructor.loadWaiterConfig (/var/runtime/node_modules/aws-sdk/lib/resource_waiter.js:196:32)
at new constructor (/var/runtime/node_modules/aws-sdk/lib/resource_waiter.js:64:10)
at features.constructor.waitFor (/var/runtime/node_modules/aws-sdk/lib/service.js:271:18)
at Object.defaultInvokeFunction [as invokeFunction] (/var/task/outbound.js:1:826)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async invokeUserFunction (/var/task/framework.js:1:2149)
at async onEvent (/var/task/framework.js:1:365)
at async Runtime.handler (/var/task/cfn-response.js:1:1543) (RequestId: f134e50c-5ed8-4bc2-a583-ea457527454c)
```

### Expected Behavior

the deploy should succeed

### Current Behavior

`cdk deploy` is failing

### Reproduction Steps

Just follow the steps here `https://aws-quickstart.github.io/cdk-eks-blueprints/getting-started/`

Not sure why is it not working!

### CDK CLI Version

2.66.1

### EKS Blueprints Version

1.6.0

### Node.js Version

v19.8.1

### Environment details (OS name and version, etc.)

OSX

**Comment by Feder1co5oave** [comment] 2023-03-26 17:08
Might be related to https://github.com/aws/aws-cdk/issues/24358#issuecomment-1460136146

Try putting `"@aws-cdk/customresources:installLatestAwsSdkDefault": true` in your CDK context

**Comment by alex-treebeard** [comment] 2023-04-16 19:03
> Might be related to [aws/aws-cdk#24358 (comment)](https://github.com/aws/aws-cdk/issues/24358#issuecomment-1460136146)
> 
> Try putting `"@aws-cdk/customresources:installLatestAwsSdkDefault": true` in your CDK context

I tried this and am still seeing the error. I also tried downgrading to an older cdk version as recommended in that issue.

**Comment by Sean-McAuliffe** [comment] 2023-06-07 17:53
still running into this....any fixes? saw the other threads about this and followed those instructions, everything updated, etc. still running into the same error. used the EKS Blueprints tutorial to test. really don't want to go back to terraform since we're committed to staying on AWS, but not seeing much choice here.

**Comment by shapirov103** [comment] 2023-06-07 18:13
@Sean-McAuliffe We could not reproduce this issue, we are running our EKS Blueprints workshop (https://catalog.workshops.aws/eks-blueprints-for-cdk/en-US) successfully over the last several months. can you please point me to the specific tutorial section that results in this issue?

**Comment by Sean-McAuliffe** [comment] 2023-06-07 20:00
@shapirov103  - the get started page. we're using it to introduce an intern to the CDK/EKS in general. deployed once OK in east-2, then we had the intern tear it down, replace the autoscale addon with Karpenter, and redeploy.  First error was the above re: functionActiveV2, second one we got is this:


`Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: Resource is not in the state functionActive` 

we've been able to get this error to happen in relation to:


we tried with the most up-to-date CDK version, tried to downgrade to under 2.60, and added `"@aws-cdk/customresources:installLatestAwsSdkDefault": true` to his cdk.context.json file

**Comment by Beenhakker** [comment] 2023-06-08 09:09
@shapirov103 @Sean-McAuliffe I can confirm the exact same thing. Just following through the main guide. This is the one I used: https://aws-quickstart.github.io/cdk-eks-blueprints/getting-started/

Day before yesterday deployed a stack for the first time on "eu-central-1", tore it down, and tried spinning it up again yesterday, and received the following error. Tried upgrading, since there were updates coincidentally so I thought it might be related, but same error today. 

Cloudstack error:
```
---
Received response status [FAILED] from custom resource. Message returned: AccessDeniedException: Resource is not in the state functionActive at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:61:27) at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:61:8) at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14) at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12) at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12) (RequestId: 10f3132d-1390-46df-ae79-ff0555e2d3b1)
---
```

**Comment by Sean-McAuliffe** [comment] 2023-06-09 13:27
looking through this a bit, looks like there are a few other open issues on this too. *really* don't want to, but seems I have to go back to terraform for now until this is resolved.

**Comment by zjaco13** [comment] 2023-06-09 19:01
Hi there! We are actively looking into this.

**Comment by zjaco13** [comment] 2023-06-09 20:38
I ran through the getting started page from scratch, and was unable to reproduce this issue.

One possible problem could be that the region the stack is supposed to deploy to (us-east-2) is not the region bootstrapped when you run `cdk bootstrap`, since that will bootstrap the default region in your AWS credentials.  If you want to make sure you are bootstrapping the correct region, you can run `cdk bootstrap aws://<ACCOUNT-NUMBER>/us-east-2`

Also, currently the Cloud AutoScaling addon requires a helm chart version, so that line from the getting started page should go `new blueprints.addons.ClusterAutoScalerAddOn({ version: "9.29.0" })`. This is temporary, and a solution should be merged within the next few days.

**Comment by Sean-McAuliffe** [comment] 2023-06-09 21:53
> I ran through the getting started page from scratch, and was unable to reproduce this issue.
> 
> One possible problem could be that the region the stack is supposed to deploy to (us-east-2) is not the region bootstrapped when you run `cdk bootstrap`, since that will bootstrap the default region in your AWS credentials. If you want to make sure you are bootstrapping the correct region, you can run `cdk bootstrap aws://<ACCOUNT-NUMBER>/us-east-2`
> 
> Also, currently the Cloud AutoScaling addon requires a helm chart version, so that line from the getting started page should go `new blueprints.addons.ClusterAutoScalerAddOn({ version: "9.29.0" })`. This is temporary, and a solution should be merged within the next few days.

hey @zjaco13 - appreciate the reply. We were bootstrapped, promise. I think given that there's 4-6 other issues open for this, we can treat it as a legit bug and not user error

**Comment by Beenhakker** [comment] 2023-06-10 12:40
@zjaco13 Thanks for this. 

Yes, definitely bootstrapped as well.

You say you "followed the guide", but that was just one step when things went wrong with us. 

Both @Sean-McAuliffe first provisioned a cluster via the steps from the guide, then tore the cluster down, and _then_ tried to provision a new cluster. _That_ is the moment went things go wrong.

@zjaco13 Can you confirm you actually went through these steps? Because it is not clear from your remark. Thanks.

**Comment by zjaco13** [comment] 2023-06-12 17:16
@Beenhakker @Sean-McAuliffe Thank you for letting me know! I have also torn down the stack and re-provisioned it without any hiccups.  While tearing down the stack with did any warnings or errors come up? Also, how did you go about tearing down the stack, `cdk destroy` or in the console?

**Comment by Beenhakker** [comment] 2023-06-14 08:53
@zjaco13 I used `cdk destroy`. Can't recall if any errors showed up.

**Comment by zjaco13** [comment] 2023-06-15 16:41
@Beenhakker, I'm still unable to reproduce this issue when testing in `eu-central-1`

**Comment by shapirov103** [comment] 2023-06-16 15:43
@Sean-McAuliffe we would certainly consider shipping you the machine, but we do most of our dev in the cloud. 
We can attempt to reproduce with node exporter in place, but it seems orthogonal to the issue. Is there anything particular that you can share with respect to your IAM setup? What permissions your identity has?

Also do you mind trying our [patterns](https://github.com/aws-samples/cdk-eks-blueprints-patterns) repo, e.g. our starter construct `make pattern starter deploy` ?

**Comment by Sean-McAuliffe** [comment] 2023-06-16 16:14
@shapirov103  - 

I've tried this via a few IAM roles, all of which have full access to EKS & services needed to support the EKS cluster

Even tried from root on my personal account just to make sure, same error. 


I remember when some folks were getting a similar error, `Resource is not in the state functionActiveV2` - any chance that when that particular bug was fixed, someone just forgot to update an extra file?

**Comment by zjaco13** [comment] 2023-06-28 18:31
@Sean-McAuliffe did you have any success with deploying a pattern from the patterns repo?

**Comment by elamaran11** [comment] 2023-10-12 12:33
@imshashank @Sean-McAuliffe  Closing this issue as we have not heardback in 4 months. Please reach back if you still face issues.

**Closed by elamaran11** 2023-10-12 12:33 UTC
Labels: bug
