### ISSUE TITLE
Managed Node Group Cluster Provider: KubectlLayer comparison is false

### ISSUE THREAD

**Issue by pennywisdom** [aws-quickstart/cdk-eks-blueprints#740] opened 2023-06-22 11:11 UTC
### Describe the bug

When using the Managed Node Group Cluster Provider we are receiving the following warning:
"[Warning at /dev-harness-infrastructure-cluster/dev-harness-infrastructure-cluster] You created a cluster with Kubernetes Version 1.25 without specifying the kubectlLayer property. This may cause failures as the kubectl version provided with aws-cdk-lib is 1.20, which is only guaranteed to be compatible with Kubernetes versions 1.19-1.21. Please provide a kubectlLayer from @aws-cdk/lambda-layer-kubectl-v25]"

We are setting the cluster version as follows:

```javascript
const k8sVersion = KubernetesVersion.V1_25
const clusterId = `${id}-cluster`
this.blueprintStack = builder
  .version(k8sVersion)
  .addOns(...addOns)
  .clusterProvider(mngProvider)
  .enableControlPlaneLogTypes(...logTypes)
  .teams(new PlatformTeam(`${id}-team`, platformTeamRole))
  .build(scope, clusterId, props)
```

### Expected Behavior

The appropriate layer for v1.25 should be matched in the condition and used.

### Current Behavior

The switch statement is comparing objects and not evaluating to the correct version.

### Reproduction Steps

Create a new blueprint similar to:

```javascript
const k8sVersion = KubernetesVersion.V1_25
const clusterId = `${id}-cluster`
this.blueprintStack = builder
  .version(k8sVersion)
  .addOns(...addOns)
  .clusterProvider(mngProvider)
  .enableControlPlaneLogTypes(...logTypes)
  .teams(new PlatformTeam(`${id}-team`, platformTeamRole))
  .build(scope, clusterId, props)
```

run 
```bash
cdk diff
```
A warning will be logged to the console.

### Possible Solution

In the [getKubectlLayer](https://github.com/aws-quickstart/cdk-eks-blueprints/blob/48d677e4849a356979211cd394793df47c06f815/lib/cluster-providers/generic-cluster-provider.ts#L284) function, its is comparing objects and failing whereas comparing the string version i.e. ```version.version``` against the KubernetesVersion then the layer version is correctly determined.

e.g.

```javascript
const getKubectlLayer = (scope, version) => {
  switch (version.version) {
    case eks.KubernetesVersion.V1_25.version:
      return new lambdaLayerKubectlv25.KubectlV25Layer(scope, 'kubectllayer25')
    case eks.KubernetesVersion.V1_26.version:
      return new lambdaLayerKubectlv26.KubectlV26Layer(scope, 'kubectllayer26')
  }

  const minor = version.version.split('.')[1]
  if (minor && parseInt(minor, 10) > 26) {
    return new lambdaLayerKubectlv26.KubectlV26Layer(scope, 'kubectllayer26') // for all versions above 1.25 use 1.25 kubectl (unless explicitly supported in CDK)
  }

  return undefined
}
```

### CDK CLI Version

2.84.0

### EKS Blueprints Version

1.9.1

### Node.js Version

18

### Environment details (OS name and version, etc.)

Ubuntu 20.04.6 LTS

### Other information

Similar to #607

**Comment by shapirov103** [comment] 2023-08-29 20:25
@pennywisdom I believe this was addressed in the latest versions, e.g 1.11.0. Please let me know if you still experience this behavior.

**Comment by elamaran11** [comment] 2023-10-12 12:26
@pennywisdom Closing this issue as the issue is addressed and we have not heard back. Please reach back if you still face this issue.

**Closed by elamaran11** 2023-10-12 12:26 UTC
Labels: bug
