### ISSUE TITLE
more programming languages support

### ISSUE THREAD

**Issue by zxkane** [aws-quickstart/cdk-eks-blueprints#475] opened 2022-08-13 06:42 UTC
### Describe the feature

CDK EKS bludprints is built on AWS CDK, which support multiple programming languages. It would be useful to support additional programming languages(Python, Java, Go, C#) of EKS blueprints.

### Use Case

Use another programming language besides TS to deploy the infra with EKS.

### Acknowledgements

- [ ] I may be able to implement this feature request

### CDK version used

2.x

### Node.js Version

14.x

### Environment details (OS name and version, etc.)

MacOSX, Ubuntu 18.04

**Comment by shapirov103** [comment] 2022-10-24 15:17
The baseline is: at the moment we only support `typescript/nodejs` since we are taking advantage of the language features, such as OO, functional programming constructs, etc. We are researching using JSII support for code generation. If we are successful with that, we can quickly roll out most of the languages supported by CDK, including Java, C#, Go, etc.

**Comment by askulkarni2** [comment] 2022-11-03 17:07
Duplicate of #98

**Closed by askulkarni2** 2022-11-03 17:07 UTC
Labels: feature
